image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver

build_script:
  - ps: .\build.ps1
  
test:
  assemblies:
    only:
      - '**\*tests.dll'

after_build:
  - 7z a .\code_drop\packages\RoundhousE.%GitVersion_SemVer%.zip .\code_drop\tmp\RoundhousE
  - 7z a .\code_drop\packages\RoundhousE.tar .\code_drop\tmp\RoundhousE
  - 7z a .\code_drop\packages\RoundhousE.%GitVersion_SemVer%.tar.gz .\code_drop\packages\RoundhousE.tar
  
      
artifacts:
  - path: .\code_drop\packages\*.nupkg
    name: Nuget packages
  - path: .\code_drop\packages\*.tar.gz
    name: Dotnet core .tar.gz distro
  - path: .\code_drop\packages\*.zip
    name: Dotnet core .zip distro
  - path: .\code_drop\log\*
    name: Logs

deploy:
  provider: NuGet
  server:  https://www.myget.org/F/roundhouse/api/v2/package
  api_key:
    secure: XWER/H0IkJ8JWFm+n3/lr7hHoNFAX/VpRD+AfpZo2EUgQkQKhrMxHa4aYZPogsvY
  skip_symbols: true 
  artifact: /.*\.nupkg/
  disable_publish_on_pr: true